### ISSUE TITLE
Feature:  thumps up, down

### ISSUE THREAD

**Issue by wowario** [wownero/wownero-funding-system#18]
registered users are able to thumps up, down proposals to show support or rejection of proposal

**Comment by xmrdsc** [comment]
If someone is looking to implement this; I'd add 2 columns to the `proposals` table: `upvotes` and `downvotes`.

Both could be `(SMALL)INT`, it would allow for easy increment/decrement of proposals, but you wouldnt see who upvoted/downvoted what.

If you'd want to see that too, I'd suggest one column, a Postgres `JSONB` type + using the module `sqlalchemy_json` to save JSON blobs and have some structure in there that keeps track of `user.id`'s associated with upvotes/downvotes.
